# docker-compose.yml

services:
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --host=0.0.0.0 --port=8000 --reload"
    container_name: fastapi_university
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/app:z